### ISSUE TITLE
Adding to policejob menu error

### ISSUE THREAD

**Issue by mrquim** [apoiat/ESX_CommunityService#2]
Hi, im trying to add it to esx_policejob menu, but im getting this error - http://prntscr.com/nkeuw1

This is what i add to main.lua from esx_policejob  - http://prntscr.com/nkev9f

What i did wrong? And thnxs for create this amazing script <3 :D

**Comment by apoiat** [comment]
You have a syntax error at line 676. Can you post all client/main.lua from your esx_policejob?

**Comment by mrquim** [comment]
https://pastebin.com/raw/hcYBrx03

**Comment by apoiat** [comment]
You have improperly attached the code provided in the README.md. There are 3 code segments that need to be added in specific places. Search for the code before the -- add this part of code in the Readme.md and try again.

**Comment by mrquim** [comment]
Yes, you were right. I had misunderstood. I got it. Thank you very much
